require('./MainPublicCtrl');
require('./MainPrivateCtrl');
require('./AdminCtrl');
require('./JobsCtrl');
require('./PropertiesCtrl');
require('./WorkersCtrl');
require('./WorkersEditCtrl');
require('./ReportsCtrl');
require('./DashCtrl');
